#!/bin/bash
# =============================================================================
# Generate .cursorindexingignore from .gitignore (Single Source of Truth)
# =============================================================================
# Purpose: Maintain SST for ignored files using three-file architecture
# Usage: ./generate-cursorindexingignore.sh [--dry-run]
#
# Three-File SST Architecture:
# 1. .gitignore                      → Master for Git exclusions (494 lines)
# 2. .cursorindexingignore.additions → Master for Cursor-only exclusions (~160 lines)
# 3. .cursorindexingignore           → Generated combination (DO NOT EDIT)
#
# Rationale:
# - .gitignore is the SST for "Git unwanted" files
# - .cursorindexingignore.additions is the SST for "Cursor unwanted but Git OK" files
# - .cursorindexingignore is generated automatically (prevents duplication/drift)
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
GITIGNORE="$PROJECT_ROOT/.gitignore"
ADDITIONS="$PROJECT_ROOT/.cursorindexingignore.additions"
OUTPUT="$PROJECT_ROOT/.cursorindexingignore"

DRY_RUN=false
if [[ "$1" == "--dry-run" ]]; then
    DRY_RUN=true
    OUTPUT="/dev/stdout"
fi

# =============================================================================
# Validation
# =============================================================================

if [[ ! -f "$GITIGNORE" ]]; then
    echo "ERROR: .gitignore not found at $GITIGNORE" >&2
    exit 1
fi

if [[ ! -f "$ADDITIONS" ]]; then
    echo "ERROR: .cursorindexingignore.additions not found at $ADDITIONS" >&2
    echo "This file should contain Cursor-specific exclusions (not in .gitignore)" >&2
    exit 1
fi

# =============================================================================
# Generate .cursorindexingignore
# =============================================================================

cat > "$OUTPUT" << HEADER
# ============================================================================
# Cursor AI Indexing Exclusions for HAFiscal Project
# ============================================================================
# AUTOGENERATED - DO NOT EDIT DIRECTLY
# Generated by: @resources/scripts/generate-cursorindexingignore.sh
#
# Single Source of Truth (SST) Three-File Architecture:
# 1. .gitignore                      → Master for Git exclusions
# 2. .cursorindexingignore.additions → Master for Cursor-only exclusions
# 3. .cursorindexingignore           → GENERATED (this file)
#
# To regenerate: make cursor-indexing-ignore
#
# To add new exclusions:
# - If file should be excluded from Git: Add to .gitignore
# - If file should only be excluded from Cursor: Add to .cursorindexingignore.additions
# - Then run: make cursor-indexing-ignore
# ============================================================================

# ============================================================================
# SECTION 1: Patterns from .gitignore
# ============================================================================
# All patterns from .gitignore are included below.
# If something is excluded from Git, it should also be excluded from indexing.
#
# Source: .gitignore ($(wc -l < "$GITIGNORE" | tr -d ' ') lines)

HEADER

# Extract non-comment, non-empty patterns from .gitignore
# Exclude negations (!) and self-references
grep -v '^#' "$GITIGNORE" | \
    grep -v '^$' | \
    grep -v '^!' | \
    grep -v '^\.cursorindexingignore' | \
    grep -v '^\.cursorignore' >> "$OUTPUT"

# =============================================================================
# Add Cursor-specific exclusions from .additions file
# =============================================================================

cat >> "$OUTPUT" << DIVIDER

# ============================================================================
# SECTION 2: Cursor-Specific Additional Exclusions
# ============================================================================
# Patterns for files that ARE in Git but should NOT be indexed by Cursor.
# These patterns exclude files for performance or privacy reasons.
#
# Source: .cursorindexingignore.additions ($(wc -l < "$ADDITIONS" | tr -d ' ') lines)

DIVIDER

# Extract non-comment, non-empty patterns from .additions file
grep -v '^#' "$ADDITIONS" | \
    grep -v '^$' | \
    grep -v '^!' >> "$OUTPUT"

# =============================================================================
# Add footer
# =============================================================================

cat >> "$OUTPUT" << FOOTER

# ============================================================================
# END OF AUTOGENERATED FILE
# ============================================================================
# Total patterns: $(grep -v '^#' "$OUTPUT" | grep -v '^$' | wc -l | tr -d ' ')
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
#
# To add new exclusions:
# 1. Determine if file should be in Git:
#    - NO (exclude from Git) → Add to .gitignore
#    - YES (in Git but don't index) → Add to .cursorindexingignore.additions
# 2. Regenerate: make cursor-indexing-ignore
# 3. Reload Cursor: Cmd+Shift+P → "Developer: Reload Window"
# ============================================================================
FOOTER

if [[ "$DRY_RUN" == false ]]; then
    PATTERN_COUNT=$(grep -v '^#' "$OUTPUT" | grep -v '^$' | wc -l | tr -d ' ')
    TOTAL_LINES=$(wc -l < "$OUTPUT" | tr -d ' ')
    
    echo "✅ Generated: $OUTPUT"
    echo "   Total lines: $TOTAL_LINES"
    echo "   Patterns: $PATTERN_COUNT"
    echo ""
    echo "   Sources:"
    echo "     - .gitignore: $(wc -l < "$GITIGNORE" | tr -d ' ') lines"
    echo "     - .cursorindexingignore.additions: $(wc -l < "$ADDITIONS" | tr -d ' ') lines"
    echo ""
    echo "Next steps:"
    echo "  1. Review: cat .cursorindexingignore | head -50"
    echo "  2. Reload Cursor: Cmd+Shift+P → 'Developer: Reload Window'"
    echo "  3. Test: Cmd+P → type 'HAFiscal.pdf' (should NOT appear)"
    echo "  4. Test: Cmd+P → type 'reproduce.sh' (SHOULD appear)"
fi
